//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupProjectDonation272.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Center
    {
        public int CenterID { get; set; }
        public string Name { get; set; }
        public string PhysicalAddress { get; set; }
        public string EmailAddress { get; set; }
        public int ContactNumber { get; set; }
    
        public virtual Courier Courier { get; set; }
        public virtual CenterType CenterType { get; set; }
    }
}
