//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupProjectDonation272.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int DeliveryID { get; set; }
        public int DonationSize { get; set; }
    
        public virtual CourierDelivery1 CourierDelivery1 { get; set; }
        public virtual DeliveryStatu DeliveryStatu { get; set; }
    }
}
