//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupProjectDonation272.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryStatu
    {
        public int DeliveryStatusID { get; set; }
        public string Delivered { get; set; }
        public string InTransit { get; set; }
    
        public virtual Delivery Delivery { get; set; }
    }
}
