//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupProjectDonation272.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        public int DonationID { get; set; }
        public string DonationName { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Donee Donee { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Stationary Stationary { get; set; }
    }
}
