//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupProjectDonation272.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DonationFinalEntities1 : DbContext
    {
        public DonationFinalEntities1()
            : base("name=DonationFinalEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<BookType> BookTypes { get; set; }
        public virtual DbSet<Center> Centers { get; set; }
        public virtual DbSet<CenterType> CenterTypes { get; set; }
        public virtual DbSet<Courier> Couriers { get; set; }
        public virtual DbSet<CourierDelivery1> CourierDelivery1 { get; set; }
        public virtual DbSet<Delivery> Deliveries { get; set; }
        public virtual DbSet<DeliveryStatu> DeliveryStatus { get; set; }
        public virtual DbSet<Donation> Donations { get; set; }
        public virtual DbSet<Donee> Donees { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Sponsor> Sponsors { get; set; }
        public virtual DbSet<SponsorType> SponsorTypes { get; set; }
        public virtual DbSet<Stationary> Stationaries { get; set; }
        public virtual DbSet<StationaryType> StationaryTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
